### ISSUE TITLE
ConeComputer ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mbtaylor** [cds-astro/cds-healpix-java#12]
If I run this:
```
        Healpix.getNested( 6 )
               .newConeComputer( 0.9886484667476922 )
               .overlappingCells( 4.646003386280478, -0.41602905223485265 );
```
I get
```
java.lang.ArrayIndexOutOfBoundsException: 1020
        at cds.healpix.NestedSmallCellApproxedMethod.buildMocRecursively(NestedSmallCellApproxedMethod.java:230)
```
Is my cone too big?

**Comment by fxpineau** [comment]
The problem was due to a too small estimate of the number of cells in the output MOC.  
If Java were supporting collections on primitives, I would have used an ArrayList<long> using the estimate as initial capacity.  
So far, I simplify the estimate and take a more conservative value.  
I promise that if you encounter again a problem, I will make the effort to implement a grow-able object.
So I close this issue for the time being.

**Comment by mbtaylor** [comment]
Thanks.  If you do decide to use a growable object, I have primitive list implementations at https://github.com/Starlink/starjava/blob/master/util/src/main/uk/ac/starlink/util/LongList.java etc which you're welcome to pinch if you like (I don't suggest making a dependency on my library, just cut'n'paste the code as required).
