### ISSUE TITLE
IllegalArgumentException in some cases for overlappingCells

### ISSUE THREAD

**Issue by mbtaylor** [cds-astro/cds-healpix-java#13]
The following call

    cds.healpix.Healpix.getNested(11)
                       .newConeComputerApprox(5./3600.)
                       .overlappingCells(0.5*Math.PI, -1.1617);

fails:

    java.lang.IllegalArgumentException: Hash value 819199 must be in [0, 786432[

This was reported as a stilts regression bug by @bourgesl.

**Comment by fxpineau** [comment]
Thank you @mbtaylor and @bourgesl for the report.  
This was due to numerical inaccuracies in `HealpixNestedHashComputer` in polar caps on (or very very close from) the `lon=n*PI/2` meridians. `HealpixNestedFast` was ok.  
It was as known issue fixed in the Rust library and I finally fixed it in the Java lib.
I wrongly assumed that "cone approx" was using  `HealpixNestedFast`.
